#!/usr/bin/env python 
# Written by Joseph Bull, 2016
# Copyright Joseph Bull 2016, All Rights Reserved

import re, os, argparse

def getArgs():
    parser = argparse.ArgumentParser(description='Parses AMI ID from packer output')
    parser.add_argument("--data", help="The last line of a packer output file.")
    args = parser.parse_args()
    return args

def getAmiId(data):
    regexSearch = re.search("([A-Za-z0-9].+): (.+)", data)
    amiId = ""
    if regexSearch != None:
        try:
            amiId = regexSearch.group(2)
        except:
            raise
    return amiId

if __name__ == "__main__":
    args = getArgs()
    if (args.data):
        print "Parsing data..."
        print args.data
        data = str(args.data)
        data = data.strip()
        amiId = getAmiId(data)
        if amiId == "":
            raise IOError("Unable to extract AMI ID.  Failing Build...")
        with open("ami_id.txt", "w") as theAmiFile:
            theAmiFile.write("AMI_ID=" + amiId)
        print "ami_id.txt successfully created"
    else:
        raise IOError("Improper data sent to getAmi File")
